package com.alextos.cashback.core.domain.models.predefined

val PredefinedCategory.emoji: String
    get() = when(this) {
        PredefinedCategory.ALL_PURCHASES -> "💵"
        PredefinedCategory.EDUCATION -> "🎓"
        PredefinedCategory.AIRPLANE_TICKETS -> "✈️"
        PredefinedCategory.VIP_ZONE -> "🧳"
        PredefinedCategory.CAR_RENT -> "🚗"
        PredefinedCategory.RAILROAD_TICKETS -> "🚂"
        PredefinedCategory.TOUR_AGENCIES -> "🌴"
        PredefinedCategory.CRUISES -> "🛳️"
        PredefinedCategory.HOTELS -> "🏨"
        PredefinedCategory.DUTY_FREE_SHOPS -> "💸"
        PredefinedCategory.TRANSPORT -> "🚇"
        PredefinedCategory.TAXI -> "🚕"
        PredefinedCategory.CAR_SHARING -> "🚙"
        PredefinedCategory.AUTO_SERVICES -> "🔧"
        PredefinedCategory.PHARMACIES -> "💊"
        PredefinedCategory.BEAUTY_AND_SPA -> "💆‍♀"
        PredefinedCategory.COSMETICS_AND_PARFUME -> "💄"
        PredefinedCategory.HOUSE_AND_RENOVATION -> "🏠"
        PredefinedCategory.ART -> "🎨"
        PredefinedCategory.BOOKS -> "📚"
        PredefinedCategory.ZOO_GOODS -> "🐶"
        PredefinedCategory.CINEMA -> "🎬"
        PredefinedCategory.ENTERTAINMENT -> "🎳"
        PredefinedCategory.EXHIBITIONS_AND_MUSEUMS -> "🖼️"
        PredefinedCategory.MEDICINE_SERVICES -> "🏥"
        PredefinedCategory.FITNESS -> "🏃‍♂️"
        PredefinedCategory.CLINICS_AND_ESTHETICS -> "💉"
        PredefinedCategory.DENTIST -> "🦷"
        PredefinedCategory.MUSIC -> "🎵"
        PredefinedCategory.SUPERMARKETS -> "🛒"
        PredefinedCategory.SHOPS -> "🛍️"
        PredefinedCategory.ELECTRONIC_DEVICES -> "📱"
        PredefinedCategory.RESTAURANTS -> "🍽️"
        PredefinedCategory.FASTFOOD -> "🍕"
        PredefinedCategory.COMMUNICATION_AND_TELECOM -> "📶"
        PredefinedCategory.PHOTO_AND_VIDEO -> "📷"
        PredefinedCategory.SOUVENIRS -> "🗼"
        PredefinedCategory.FLOWERS -> "🌹"
        PredefinedCategory.SPORT_GOODS -> "⚽"
        PredefinedCategory.CLOTHES_AND_SHOES -> "👠"
        PredefinedCategory.SBP -> "🤳🏻"
        PredefinedCategory.DIGITAL_GOODS -> "👾"
        PredefinedCategory.YANDEX -> "\uD83D\uDFE0"
        PredefinedCategory.BURGER_KING -> "🍔"
        PredefinedCategory.GAS_STATION -> "⛽"
        PredefinedCategory.COMMUNAL_SERVICES -> "🚰"
        PredefinedCategory.ACCESSORIES -> "💍"
        PredefinedCategory.SBER -> "\uD83D\uDFE2"
    }