package com.alextos.cashback.core.domain.predefined

val PredefinedCategory.localization: String
    get() = when (this) {
        PredefinedCategory.ALL_PURCHASES -> "Все покупки"
        PredefinedCategory.EDUCATION -> "Образование"
        PredefinedCategory.AIRPLANE_TICKETS -> "Авиабилеты"
        PredefinedCategory.VIP_ZONE -> "VIP залы"
        PredefinedCategory.CAR_RENT -> "Аренда авто"
        PredefinedCategory.RAILROAD_TICKETS -> "Ж/Д билеты"
        PredefinedCategory.TOUR_AGENCIES -> "Турагенства"
        PredefinedCategory.CRUISES -> "Круизы"
        PredefinedCategory.HOTELS -> "Отели"
        PredefinedCategory.DUTY_FREE_SHOPS -> "Duty Free магазины"
        PredefinedCategory.TRANSPORT -> "Транспорт"
        PredefinedCategory.TAXI -> "Такси"
        PredefinedCategory.CAR_SHARING -> "Каршеринг"
        PredefinedCategory.AUTO_SERVICES -> "Автоуслуги"
        PredefinedCategory.PHARMACIES -> "Аптеки"
        PredefinedCategory.BEAUTY_AND_SPA -> "Красота и СПА"
        PredefinedCategory.COSMETICS_AND_PARFUME -> "Косметика и парфюм"
        PredefinedCategory.HOUSE_AND_RENOVATION -> "Дом и ремонт"
        PredefinedCategory.ART -> "Искусство"
        PredefinedCategory.BOOKS -> "Книги"
        PredefinedCategory.ZOO_GOODS -> "Зоотовары"
        PredefinedCategory.CINEMA -> "Кино"
        PredefinedCategory.ENTERTAINMENT -> "Развлечения"
        PredefinedCategory.EXHIBITIONS_AND_MUSEUMS -> "Выставки и музеи"
        PredefinedCategory.MEDICINE_SERVICES -> "Медицинские услуги"
        PredefinedCategory.FITNESS -> "Фитнес"
        PredefinedCategory.CLINICS_AND_ESTHETICS -> "Клиники и эстетическая медицина"
        PredefinedCategory.DENTIST -> "Стоматологии"
        PredefinedCategory.MUSIC -> "Музыка"
        PredefinedCategory.SUPERMARKETS -> "Супермаркеты"
        PredefinedCategory.SHOPS -> "Магазины"
        PredefinedCategory.ELECTRONIC_DEVICES -> "Электроника и бытовая техника"
        PredefinedCategory.RESTAURANTS -> "Рестораны и кафе"
        PredefinedCategory.FASTFOOD -> "Фастфуд"
        PredefinedCategory.COMMUNICATION_AND_TELECOM -> "Коммуникации и телеком"
        PredefinedCategory.PHOTO_AND_VIDEO -> "Фото и видео"
        PredefinedCategory.SOUVENIRS -> "Сувениры"
        PredefinedCategory.FLOWERS -> "Цветы"
        PredefinedCategory.SPORT_GOODS -> "Спорттовары"
        PredefinedCategory.CLOTHES_AND_SHOES -> "Одежда и обувь"
        PredefinedCategory.SBP -> "QR-код СБП"
        PredefinedCategory.DIGITAL_GOODS -> "Цифровые товары"
        PredefinedCategory.YANDEX -> "Сервисы Яндекса"
        PredefinedCategory.BURGER_KING -> "Бургер Кинг"
        PredefinedCategory.GAS_STATION -> "Заправки"
        PredefinedCategory.COMMUNAL_SERVICES -> "Коммунальные услуги"
        PredefinedCategory.ACCESSORIES -> "Аксессуары"
    }